### getAll
GET http://localhost:8080/api/v1/zapatillas

### getAll (RequestParam)
GET http://localhost:8080/api/v1/zapatillas?numero=1234-5678-1234-5678

### getAll  (RequestParam)
GET http://localhost:8080/api/v1/tarjetas?numero=1234-5678-1234-5678&titular=Juan

### getAll  (RequestParam)
GET http://localhost:8080/api/v1/tarjetas?titular=Jose

### getById
GET http://localhost:8080/api/v1/zapatillas/1

### getById (una que no existe)
GET http://localhost:8080/api/v1/zapatillas/3

### Nueva tarjeta
POST http://localhost:8080/api/v1/zapatillas
Content-Type: application/json

{
  "marca": "New Balance",
  "modelo": "9090",
  "codigoProducto": "NB1234CE",
  "talla": 42,
  "color": "negro",
  "tipo": "Running",
  "precio": 59.99,
  "stock": 10
}

### Actualiza tarjeta
PUT http://localhost:8080/api/v1/tarjetas/1
Content-Type: application/json

{
  "numero": "2222-5678-1234-5678",
  "cvc": "321",
  "fechaCaducidad": "2029-12-31",
  "titular": "María",
  "saldo": 300.0
}


### Delete tarjeta
DELETE http://localhost:3000/api/v1/tarjetas/2