drop table if exists ZAPATILLAS;

create table ZAPATILLAS
(
    id             bigint generated by default as identity PRIMARY KEY,
    marca          varchar(50)                         not null,
    modelo         varchar(100)                        not null,
    codigoProducto varchar(10)                         not null,
    talla          float(50)                           not null,
    color          varchar(50)                         not null,
    tipo           varchar(20)                         not null,
    precio         float(52)                           not null,
    stock          bigint                              not null,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid           uuid                                not null unique
);
INSERT INTO ZAPATILLAS(marca, modelo, codigoProducto, talla, color, tipo, precio,
                       stock,uuid)
VALUES ( 'Nike','Air Max','NI1234KE',42.0,'Rojo','Running',
        89.99,28,UUID());

INSERT INTO ZAPATILLAS(marca, modelo, codigoProducto, talla, color, tipo, precio,
                       stock, uuid)
VALUES ( 'Fila','high','FI1234LA',40.0,'Blanco','Running',
         79.99,52,UUID());