### getAll
GET http://localhost:3000/api/v1/zapatillas

### getAll (RequestParam - marca)
GET http://localhost:3000/api/v1/zapatillas?marca=Nike

### getAll (RequestParam - marca y tipo)
GET http://localhost:3000/api/v1/zapatillas?marca=Adidas&tipo=Running

### getAll (RequestParam - tipo)
GET http://localhost:3000/api/v1/zapatillas?tipo=Casual

### getById
GET http://localhost:3000/api/v1/zapatillas/1

### getById (una que no existe)
GET http://localhost:3000/api/v1/zapatillas/3

### Nueva zapatilla
POST http://localhost:3000/api/v1/zapatillas
Content-Type: application/json

{
  "marca": "New Balance",
  "modelo": "9090",
  "codigoProducto": "NB1234CE",
  "talla": 42,
  "color": "negro",
  "tipo": "Running",
  "precio": 59.99,
  "stock": 10
}

### Actualiza zapatilla
PUT http://localhost:3000/api/v1/zapatillas/1
Content-Type: application/json

{
  "marca": "Nike",
  "modelo": "Air Max",
  "codigoProducto": "NK2024",
  "talla": 43,
  "color": "blanco",
  "tipo": "Casual",
  "precio": 89.99,
  "stock": 15
}

### Delete zapatilla
DELETE http://localhost:3000/api/v1/zapatillas/1