drop table if exists ZAPATILLAS;
drop table if existes USUARIOS;

create table ZAPATILLAS
(
    id             bigint generated by default as identity PRIMARY KEY,
    marca          varchar(50)                         not null,
    modelo         varchar(100)                        not null,
    codigoProducto varchar(10)                         not null,
    talla          float(50)                           not null,
    color          varchar(50)                         not null,
    tipo           varchar(20)                         not null,
    precio         float(52)                           not null,
    stock          bigint                              not null,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid           uuid                                not null unique
);
create table USUARIOS
(
    id         bigint generated by default as identity PRIMARY KEY,
    nombre     varchar(100) not null,
    email      varchar(150) not null unique,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);


